In [13]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

In [2]:
df = pd.read_csv("heloc_dataset_cleaned.csv")
X = df.drop(columns=['RiskPerformance'])
y = df['RiskPerformance']

In [ ]:
def get_bootstrap_scores(self, niter=11, bootstrap_size=0.5):
    for i in tqdm(range(niter)):
        np.random.seed(i)
        idx = np.random.permutation(self.n_train)[:int(self.n_train*bootstrap_size)]
        self.results["risk_b"+str(i)] = self.train_model(self.partition["X_tr"][idx], self.partition["y_tr"][idx])

In [25]:
predictions_df = pd.DataFrame()
# ideal = 10 random seeds,
# rn, fix random seed for traintest split
for i in range(101):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=30)
    model = RandomForestClassifier(n_estimators=25, random_state=i)
    np.random.seed(i)
    idx = np.random.permutation(len(X_train))[:int(len(X_train)*0.5)]
    print(idx)
    X_train = X_train.to_numpy()
    y_train = y_train.to_numpy()
    # self.results["risk_b"+str(i)] = self.train_model(self.partition["X_tr"][idx], self.partition["y_tr"][idx])
    model.fit(X_train[idx], y_train[idx])
    scores = model.predict_proba(X_test)[:, 1] # predict only on test
    predictions_df[f'Model_{i+1}'] = scores
    print(f"model {i} finished training")
predictions_df.to_csv('model_predictions.csv', index=False)

[6456 9398 3822 ... 6908 3080 3175]
model 0 finished training
[7303 3404 5198 ... 3109 5661  772]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 1 finished training
[4414 4986 2739 ... 1235 7116 2001]
model 2 finished training
[6975 3798 5943 ... 8389  516  458]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 3 finished training
[5577 2898  236 ... 1317 6254 3498]
model 4 finished training
[6417 5373 7389 ... 8631 7979 2560]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 5 finished training
[6390 8266  909 ... 8006 2502  176]
model 6 finished training
[6382 3676 6305 ... 8183 9142  801]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 7 finished training
[4773 5933 7869 ... 3472 9204 3592]
model 8 finished training
[ 207 4928 3942 ...  153 1611 1114]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 9 finished training
[9173 7302 5037 ...  986 5564 3674]
model 10 finished training
[6714 1855 5428 ... 7780 2581 1764]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 11 finished training
[3209 1420  266 ...  402 4940 7024]
model 12 finished training
[4855  985 8748 ...  386 3049  957]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 13 finished training
[6470 5715 8800 ... 3185 7217 6597]
model 14 finished training
[8577 6405  919 ... 7128 5244  691]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 15 finished training
[6321 3960 4830 ... 3143 4512 1687]
model 16 finished training
[8365 2670 2804 ... 1429 7202 8392]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 17 finished training
[7784 4297 6279 ... 1075 5630 4809]
model 18 finished training
[ 912 5915 1089 ... 4174 6555 1602]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 19 finished training
[4145 5260 7575 ...  868 4558 9272]
model 20 finished training
[ 608 2804 6842 ...  885 7672 7558]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 21 finished training
[7886 9030 4586 ... 8652 8460 1239]
model 22 finished training
[2989 2527 4070 ... 5439 1211 8984]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 23 finished training
[5198 4351 1548 ... 2828 3680 8955]
model 24 finished training
[1754  563 1960 ... 9348 1598 7728]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 25 finished training
[4999  620 1821 ... 2067 5564 7858]
model 26 finished training
[6435 2276 8973 ... 6326 7066 5755]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 27 finished training
[5810 3588  707 ... 2764 2641 8877]
model 28 finished training
[   1 6052 5264 ... 4130 2969 6637]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 29 finished training
[7721 1397 2358 ... 1289  280 7605]
model 30 finished training
[ 495 5590 1081 ... 2190 5221 6288]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 31 finished training
[6017  628 8702 ... 6755 5040 1937]
model 32 finished training
[9359 2456 2358 ... 3770  172 3576]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 33 finished training
[6772  509  700 ... 4768 8980 6522]
model 34 finished training
[1172 4513 6116 ... 3633  113 6792]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 35 finished training
[1851 2712 8746 ...  584 1999 3175]
model 36 finished training
[1211 9141 7500 ...  290 5472 6619]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 37 finished training
[3907 6445   31 ...  620 5715 7183]
model 38 finished training
[5172 6452  946 ... 5808 6391  219]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 39 finished training
[9238 3102  612 ... 4013 5780 3282]
model 40 finished training
[7647 1064 8938 ... 1708  953 6668]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 41 finished training
[8386 3025 9310 ...  803 6087 6239]
model 42 finished training
[7637 6889  315 ... 9399 7837 4339]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 43 finished training
[6422 1081 6927 ... 4599 2591 6628]
model 44 finished training
[6548 1067 8416 ... 3348 3054 5924]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 45 finished training
[6053 5263   22 ... 8743 7811 4688]
model 46 finished training
[5764  428 2124 ... 4712 6883 3374]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 47 finished training
[7546 2660 7449 ... 9179 1363 2760]
model 48 finished training
[1895  107 2201 ... 8355 3939 4867]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 49 finished training
[7977 6142  251 ... 2822  959 8790]
model 50 finished training
[4562 4952 8933 ... 4721 6546 5297]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 51 finished training
[3708 2797 7273 ... 3060 5231 1969]
model 52 finished training
[ 690 1674 6843 ...  807   17 7704]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 53 finished training
[5148 1774 2862 ... 2729 4971 5783]
model 54 finished training
[2984 1147 3138 ... 7791 9344 8096]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 55 finished training
[4712 4310 6157 ... 2059 7572  863]
model 56 finished training
[7910 5920 3690 ... 3209 3678 5180]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 57 finished training
[4418 7078 6579 ... 4456 4419 2171]
model 58 finished training
[ 556 1274  693 ...  424 4021 1047]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 59 finished training
[8810  104 1287 ...  393 4175 1058]
model 60 finished training
[1741 2263 5466 ... 5648  589 8263]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 61 finished training
[ 314 2140 6140 ... 7775  200 7661]
model 62 finished training
[5579 7454  992 ... 1285 4115 2137]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 63 finished training
[3001 2948 5927 ... 5150 4475   73]
model 64 finished training
[2777 4841 5734 ... 8675 8997 1266]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 65 finished training
[4436 8504  173 ... 6128  380 7754]
model 66 finished training
[3111  599 8623 ... 7858 7655 2142]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 67 finished training
[5052 9294 5015 ...  621 8184 1065]
model 68 finished training
[ 144 3084 8512 ... 8169 2559 2331]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 69 finished training
[6821 5570 2662 ... 1845  909 5920]
model 70 finished training
[2657 4000 5468 ...  780 5547 5773]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 71 finished training
[5423 5061 3939 ... 2843 8577 7149]
model 72 finished training
[4237 2274 7416 ... 4397 4156 4639]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 73 finished training
[2185 2160 2648 ... 7367 2440 3273]
model 74 finished training
[3813 7623 2261 ... 4666 7024 1655]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 75 finished training
[8403 6691 3054 ... 9285 1824 3117]
model 76 finished training
[1019 5580 9395 ... 9234 2748 8900]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 77 finished training
[ 517 4154  149 ... 7285 3308 5067]
model 78 finished training
[1668 5979  521 ... 1999 7364 1817]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 79 finished training
[5321 6880  393 ... 6108  769 1836]
model 80 finished training
[6928 8457  465 ... 4178 6431 8916]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 81 finished training
[ 452 3756 1283 ...  335 8446 1675]
model 82 finished training
[9188  996 7379 ... 3174 8306 5367]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 83 finished training
[7058 4215 2208 ... 7077 8763 5411]
model 84 finished training
[7647 4072  862 ... 2130 4590 9258]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 85 finished training
[5052 8428 2683 ... 6095 7041 1553]
model 86 finished training
[ 291 2365 9338 ... 7456 6174 5997]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 87 finished training
[3094 6048 5051 ... 7546 8859  976]
model 88 finished training
[8866 9068  356 ... 4053 1522 3566]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 89 finished training
[ 943 1079 3231 ... 2040 6083 8625]
model 90 finished training
[9074 4828 1496 ... 6052 3170 1165]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 91 finished training
[7261 6993 2429 ... 6256 2283 6835]
model 92 finished training
[4755  430 3581 ...  224 5123 6714]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 93 finished training
[2972 1195 1049 ... 5479 5820 6674]
model 94 finished training
[4112 7833 5442 ... 4840 7747 6206]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 95 finished training
[3949 3426 6784 ...   56 2688 6048]
model 96 finished training
[8102 9330 6001 ... 6596 4977 3862]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


model 97 finished training
[5421 9036 7514 ... 7008 6776 8868]
model 98 finished training
[2195 6481 3767 ... 7807 4791  898]


/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/Users/margaretwang/Library/Python/3.12/lib/python/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/var/folders/y5/ccvw8bpx4wsgp8hz7t6s7vmr0000gn/T/ipykernel_4284/2697064747.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  predictions_df[f'Model_{i+1}'] = scores


model 99 finished training
[6259 2599  525 ... 7630 8317 1298]
model 100 finished training


In [18]:
X_train.shape

(9413, 24)

In [23]:
predictions_df.head()

Model_1  Model_2  Model_3  Model_4  Model_5  Model_6  Model_7  Model_8  \
0     0.26     0.18     0.21     0.17     0.33     0.14     0.26     0.23   
1     0.37     0.28     0.35     0.50     0.26     0.46     0.38     0.27   
2     0.41     0.29     0.45     0.38     0.37     0.41     0.43     0.47   
3     0.66     0.53     0.60     0.68     0.64     0.56     0.70     0.56   
4     0.42     0.36     0.32     0.29     0.31     0.29     0.25     0.29   

   Model_9  Model_10  Model_11  
0     0.18      0.21      0.15  
1     0.32      0.34      0.49  
2     0.51      0.39      0.47  
3     0.62      0.53      0.67  
4     0.31      0.34      0.33

In [21]:
predictions_df["Model_1"].value_counts()

Model_1
0.23    24
0.32    22
0.54    19
0.26    18
0.66    18
        ..
0.04     2
0.77     2
0.99     1
0.97     1
0.02     1
Name: count, Length: 100, dtype: int64